bot_token: YOUR_BOT_TOKEN

bot:
  command_prefix: "!floodgate "
  description: A Discord bot that allows messages in channels for only a specified amount of time.

  modules:
    floodgate:
      channels:

        123456789012345678:
          gate_open:
            timezone: America/New_York
            time: 2:30 pm
            duration: 5 min
          messages:
            open: Opened on schedule
            close: Closed on schedule

        876543210987654321:
          gate_open:
            timezone: America/New_York
            time_window_start: 7 am
            time_window_end: 10 pm
            duration: 5 min
          messages:
            open: Opened randomly
            close: Closed randomly

logging:
  floodgate_logging_level: INFO
  discord_logging_level: WARNING
  output_file: ./logs/floodgate.log
  when: midnight
  interval: 1
  backup_count: 7
  format: "%(asctime)s %(levelname)s %(name)s | %(message)s"
